services:
  fastapi-app:
    build:
      context: ./fastapi-app      # Dockerfile이 위치한 디렉토리 경로
      dockerfile: Dockerfile      # Dockerfile 이름 (생략 가능, 기본값은 'Dockerfile')
    container_name: FastApi-app
    ports:
      - "5001:8000"

  sonarqube:
    image: sonarqube:26.9.0.129388-community  
    container_name: sonarqube
    read_only: true                             # 컨테이너 파일시스템 읽기 전용 (아래 볼륨과 /tmp만 쓰기 가능)
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true 
  sonarqube_extensions:
  sonarqube_logs:
  sonarqube_temp: